# Generated by Django 4.1.2 on 2022-10-16 10:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_productqueryset'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProductQuerySet',
        ),
    ]
